# Interactive, one-time local setup for IBC (IbcAlpha) + IB Gateway (#68).
#
# Writes the bot's PAPER credentials into IBC's LOCAL config.ini at
# C:\IBC\config.ini — and nowhere else. NOT under Documents: on
# OneDrive-redirected machines "MyDocuments" resolves into OneDrive, which
# both syncs the password to the cloud and diverges from the un-redirected
# path IBC reads by default (#195, IBC errorlevel 1006). C:\IBC is
# guaranteed local. The password never touches this repo, .env, or any
# remote. Re-run any time to update.
#
# Prerequisites (manual, once):
#   1. Install IB Gateway (offline installer) — note the install dir.
#   2. Install IBC from https://github.com/IbcAlpha/IBC/releases to C:\IBC.
#   3. In C:\IBC\StartGateway.bat set TWS_MAJOR_VRSN to your Gateway version
#      (e.g. 1045) AND set IBC_INI=C:\IBC\config.ini.
#   4. Set IBC_START_SCRIPT=C:\IBC\StartGateway.bat in .env (see .env.example).
#
# Run:
#   .\scripts\setup-ibc.ps1

$ErrorActionPreference = "Stop"

$ibcConfigDir = "C:\IBC"
$ibcConfig = Join-Path $ibcConfigDir "config.ini"
if (-not (Test-Path $ibcConfigDir)) {
    throw "C:\IBC not found — install IBC there first (prerequisite 2)."
}

Write-Host "=== basis IBC setup ===" -ForegroundColor Cyan
Write-Host "This writes the bot's PAPER credentials to $ibcConfig (local only)."
Write-Host ""

# The IBKR account has ONE shared paper username (Settings -> Paper Trading
# Account shows it, e.g. ozacko175) — there is no per-user "paper twin".
$username = Read-Host "PAPER username (the account's shared paper login, NOT a live username)"
if (-not $username) { throw "Username is required." }
$securePassword = Read-Host "Bot PAPER password (input hidden; stored only in the local config.ini)" -AsSecureString
$password = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePassword))
if (-not $password) { throw "Password is required." }

# Minimal IBC config for the start-on-demand paper model (design §3.1).
# Auto-restart stays OFF: the lifecycle wrapper owns start and stop.
$lines = @(
    "# Generated by basis scripts/setup-ibc.ps1 — local machine only, never committed",
    "IbLoginId=$username",
    "IbPassword=$password",
    "TradingMode=paper",
    "AcceptNonBrokerageAccountWarning=yes",
    "ReadOnlyApi=no",
    "AcceptIncomingConnectionAction=accept",
    "OverrideTwsApiPort=4002",
    "ExistingSessionDetectedAction=primary",
    "AutoRestartTime=",
    "ClosedownAt="
)
Set-Content -Path $ibcConfig -Value $lines -Encoding ascii

# Tighten ACLs: current user only.
icacls $ibcConfig /inheritance:r /grant:r "$($env:USERNAME):(R,W)" | Out-Null

Write-Host ""
Write-Host "Wrote $ibcConfig (ACL restricted to $env:USERNAME)." -ForegroundColor Green
Write-Host "Next steps:"
Write-Host "  1. Verify IBC_START_SCRIPT in .env points at your StartGateway.bat"
Write-Host "  2. One-time check: run 'pixi run executor-nightly' manually and confirm"
Write-Host "     Gateway logs in with NO 2FA prompt (paper-only usernames should not have one)"
Write-Host "  3. Register the nightly task: .\scripts\register-executor-task.ps1"
