"""Baseline schema (pre-0.7.0 — before the playbook `enabled` flag)

This is the schema as it existed before Alembic was introduced, matching
databases created up to v0.6.x. The `enabled` column arrives in the next
revision, mirroring commit 266f9ec.

Revision ID: 6640075bcc04
Revises:
Create Date: 2026-08-17 12:45:35.305974

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6640075bcc04"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "closure_post_mortems",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("position_id", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("realized_pnl", sa.Float(), nullable=False),
        sa.Column("actual_underlying_move_pct", sa.Float(), nullable=False),
        sa.Column("exit_date", sa.String(), nullable=False),
        sa.Column("exit_trigger", sa.String(), nullable=False),
        sa.Column("lesson_tags", sa.JSON(), nullable=False),
        sa.Column("user_override_logged", sa.Boolean(), nullable=False),
        sa.Column("playbook_id", sa.String(), nullable=True),
        sa.Column("playbook_version", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "market_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_regime", sa.String(), nullable=False),
        sa.Column("spy_price", sa.Float(), nullable=False),
        sa.Column("spy_sma20", sa.Float(), nullable=False),
        sa.Column("vix_close", sa.Float(), nullable=False),
        sa.Column("underlying_ivrs", sa.JSON(), nullable=False),
        sa.Column("spy_daily_return", sa.Float(), nullable=False),
        sa.Column("catalyst_dates", sa.JSON(), nullable=False),
        sa.Column("regime_scores", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "opportunity_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("playbook_id", sa.String(), nullable=False),
        sa.Column("playbook_version", sa.String(), nullable=False),
        sa.Column("generated_at", sa.String(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("outcome_if_taken", sa.Float(), nullable=True),
        sa.Column("bypass_reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playbooks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("underlying_ticker", sa.String(), nullable=False),
        sa.Column("strategy_type", sa.String(), nullable=False),
        sa.Column("execution_mode", sa.String(), nullable=False),
        sa.Column("entry_filters", sa.JSON(), nullable=False),
        sa.Column("execution_specs", sa.JSON(), nullable=False),
        sa.Column("exit_rules", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
    )
    op.create_table(
        "portfolio_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account", sa.JSON(), nullable=False),
        sa.Column("risk_profile", sa.JSON(), nullable=False),
        sa.Column("portfolio_greek_limits", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("underlying", sa.String(), nullable=False),
        sa.Column("strategy_type", sa.String(), nullable=False),
        sa.Column("execution_mode", sa.String(), nullable=False),
        sa.Column("legs", sa.JSON(), nullable=False),
        sa.Column("entry_date", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.String(), nullable=False),
        sa.Column("entry_premium", sa.Float(), nullable=False),
        sa.Column("premium_direction", sa.String(), nullable=False),
        sa.Column("current_value_per_share", sa.Float(), nullable=False),
        sa.Column("contracts", sa.Integer(), nullable=False),
        sa.Column("max_profit", sa.Float(), nullable=False),
        sa.Column("max_loss", sa.Float(), nullable=False),
        sa.Column("profit_target_per_share", sa.Float(), nullable=True),
        sa.Column("loss_limit_per_share", sa.Float(), nullable=True),
        sa.Column("break_even_upside", sa.Float(), nullable=True),
        sa.Column("break_even_downside", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("rolls", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("playbook_id", sa.String(), nullable=True),
        sa.Column("playbook_version", sa.String(), nullable=True),
        sa.Column("playbook_snapshot", sa.JSON(), nullable=True),
        sa.Column("journal", sa.JSON(), nullable=True),
        sa.Column("warnings_acknowledged", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions")
    op.drop_table("portfolio_config")
    op.drop_table("playbooks")
    op.drop_table("opportunity_records")
    op.drop_table("market_state")
    op.drop_table("closure_post_mortems")
    # ### end Alembic commands ###
