/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Config */
        get: operations["get_portfolio_config_api_portfolio_config_get"];
        put?: never;
        /** Update Portfolio Config */
        post: operations["update_portfolio_config_api_portfolio_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_api_positions_get"];
        put?: never;
        /** Create Position */
        post: operations["create_position_api_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_positions__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playbooks */
        get: operations["get_playbooks_api_playbooks_get"];
        put?: never;
        /** Create Playbook */
        post: operations["create_playbook_api_playbooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market State */
        get: operations["get_market_state_api_market_state_get"];
        put?: never;
        /** Update Market State */
        post: operations["update_market_state_api_market_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Observation */
        get: operations["get_portfolio_observation_api_portfolio_observation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountConfig */
        AccountConfig: {
            /** Total Nav */
            total_nav: number;
            /** Broker */
            broker: string;
            /** Account Type */
            account_type: string;
            /** Options Approval */
            options_approval: string;
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "PAPER";
        };
        /** EntryFilters */
        EntryFilters: {
            /** Min Ivr */
            min_ivr: number;
            /** Max Ivr */
            max_ivr: number;
            /** Vix Range */
            vix_range: [
                number,
                number
            ];
            /**
             * Required Trend
             * @enum {string}
             */
            required_trend: "ABOVE_SMA20" | "BELOW_SMA20" | "ANY";
            /** Block Catalyst 14Dte */
            block_catalyst_14dte: boolean;
            /** Require Catalyst 14Dte */
            require_catalyst_14dte: boolean;
        };
        /** ExecutionSpecs */
        ExecutionSpecs: {
            /** Target Dte */
            target_dte: number;
            /** Short Leg Delta */
            short_leg_delta: number;
            /** Long Leg Delta */
            long_leg_delta: number;
            /** Spread Width Dollars */
            spread_width_dollars: number;
            /** Straddle Atm */
            straddle_atm: boolean;
        };
        /** ExitRules */
        ExitRules: {
            /** Profit Take Pct */
            profit_take_pct: number;
            /** Stop Loss Pct */
            stop_loss_pct: number;
            /** Mandatory Exit Dte */
            mandatory_exit_dte: number;
            /** Catalyst Exit Days After */
            catalyst_exit_days_after: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarketStateSchema */
        MarketStateSchema: {
            /**
             * Current Regime
             * @enum {string}
             */
            current_regime: "CALM_BULL" | "HIGH_VOL_NEUTRAL" | "TRENDING_BEAR" | "EVENT_CATALYST";
            /** Spy Price */
            spy_price: number;
            /** Catalyst Dates */
            catalyst_dates?: string[];
        };
        /** OperationalJournalEntrySchema */
        OperationalJournalEntrySchema: {
            /** Core Thesis Rationale */
            core_thesis_rationale: string;
            /** Structural Invalidation */
            structural_invalidation: string;
            /** Expected Underlying Move Pct */
            expected_underlying_move_pct: number;
            /**
             * Pre Trade Emotional State
             * @enum {string}
             */
            pre_trade_emotional_state: "Calm" | "Anxious" | "Chasing" | "Bored";
            /**
             * Pre Trade Confidence Rating
             * @enum {integer}
             */
            pre_trade_confidence_rating: 1 | 2 | 3 | 4 | 5;
        };
        /** OptionLegSchema */
        OptionLegSchema: {
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Direction
             * @enum {string}
             */
            direction: "LONG" | "SHORT";
            /** Strike */
            strike: number;
            /** Expiration */
            expiration: string;
            /** Delta */
            delta: number;
            /** Theta */
            theta: number;
            /** Vega */
            vega: number;
            /**
             * Gamma
             * @default 0
             */
            gamma: number;
        };
        /** PlaybookDefinitionSchema */
        PlaybookDefinitionSchema: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Underlying Ticker */
            underlying_ticker: string;
            /**
             * Strategy Type
             * @enum {string}
             */
            strategy_type: "BULL_CALL_SPREAD" | "BEAR_PUT_SPREAD" | "IRON_CONDOR" | "LONG_STRADDLE" | "LONG_STRANGLE";
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "PAPER";
            entry_filters: components["schemas"]["EntryFilters"];
            execution_specs: components["schemas"]["ExecutionSpecs"];
            exit_rules: components["schemas"]["ExitRules"];
        };
        /** PortfolioConfigSchema */
        PortfolioConfigSchema: {
            account: components["schemas"]["AccountConfig"];
            risk_profile: components["schemas"]["RiskProfile"];
            portfolio_greek_limits: components["schemas"]["PortfolioGreekLimits"];
        };
        /** PortfolioGreekLimits */
        PortfolioGreekLimits: {
            /** Max Net Delta */
            max_net_delta: number;
            /** Max Net Vega */
            max_net_vega: number;
            /** Max Net Gamma */
            max_net_gamma: number;
        };
        /** PositionSchema */
        PositionSchema: {
            /** Id */
            id: string;
            /** Underlying */
            underlying: string;
            /**
             * Strategy Type
             * @enum {string}
             */
            strategy_type: "BULL_CALL_SPREAD" | "BEAR_PUT_SPREAD" | "IRON_CONDOR" | "LONG_STRADDLE" | "LONG_STRANGLE";
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "PAPER";
            /** Legs */
            legs: components["schemas"]["OptionLegSchema"][];
            /** Entry Date */
            entry_date: string;
            /** Expiration Date */
            expiration_date: string;
            /** Entry Premium */
            entry_premium: number;
            /**
             * Premium Direction
             * @enum {string}
             */
            premium_direction: "CREDIT" | "DEBIT";
            /** Current Value Per Share */
            current_value_per_share: number;
            /** Contracts */
            contracts: number;
            /** Max Profit */
            max_profit: number;
            /** Max Loss */
            max_loss: number;
            /** Profit Target Per Share */
            profit_target_per_share?: number | null;
            /** Loss Limit Per Share */
            loss_limit_per_share?: number | null;
            /** Break Even Upside */
            break_even_upside?: number | null;
            /** Break Even Downside */
            break_even_downside?: number | null;
            /** Notes */
            notes: string;
            /**
             * Rolls
             * @default 0
             */
            rolls: number;
            /**
             * Status
             * @enum {string}
             */
            status: "OPEN" | "CLOSED" | "EXPIRED";
            /** Playbook Id */
            playbook_id?: string | null;
            /** Playbook Version */
            playbook_version?: string | null;
            playbook_snapshot?: components["schemas"]["PlaybookDefinitionSchema"] | null;
            journal?: components["schemas"]["OperationalJournalEntrySchema"] | null;
        };
        /** RiskProfile */
        RiskProfile: {
            /** Max Trade Risk Pct */
            max_trade_risk_pct: number;
            /** Max Trade Risk Dollars */
            max_trade_risk_dollars: number;
            /** Max Underlying Concentration Pct */
            max_underlying_concentration_pct: number;
            /** Max Correlated Index Pct */
            max_correlated_index_pct: number;
            /** Minimum Cash Reserve Pct */
            minimum_cash_reserve_pct: number;
            /** Max Simultaneous Positions */
            max_simultaneous_positions: number;
            /** Max Capital Deployed Pct */
            max_capital_deployed_pct: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_portfolio_config_api_portfolio_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioConfigSchema"];
                };
            };
        };
    };
    update_portfolio_config_api_portfolio_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioConfigSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioConfigSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_positions_api_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"][];
                };
            };
        };
    };
    create_position_api_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playbooks_api_playbooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookDefinitionSchema"][];
                };
            };
        };
    };
    create_playbook_api_playbooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaybookDefinitionSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookDefinitionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_state_api_market_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
        };
    };
    update_market_state_api_market_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketStateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_observation_api_portfolio_observation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
