/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Config */
        get: operations["get_portfolio_config_api_portfolio_config_get"];
        put?: never;
        /** Update Portfolio Config */
        post: operations["update_portfolio_config_api_portfolio_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_api_positions_get"];
        put?: never;
        /** Create Position */
        post: operations["create_position_api_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Position Prices
         * @description Fetch delayed market prices for all open positions from IB Gateway
         *     and update their current_value_per_share in the database.
         */
        post: operations["refresh_position_prices_api_positions_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/post-mortems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post Mortems */
        get: operations["get_post_mortems_api_positions_post_mortems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_positions__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playbooks */
        get: operations["get_playbooks_api_playbooks_get"];
        put?: never;
        /** Create Playbook */
        post: operations["create_playbook_api_playbooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market State */
        get: operations["get_market_state_api_market_state_get"];
        put?: never;
        /**
         * Update Market State
         * @description Manually set all telemetry inputs. Regime is recomputed from the provided values.
         */
        post: operations["update_market_state_api_market_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Live Market State
         * @description Triggers a live fetch from IB Gateway for SPY price/SMA20/return and VIX.
         *     Recomputes and saves the regime. Returns 503 if the Gateway is unreachable
         *     or the fetch fails.
         */
        post: operations["fetch_live_market_state_api_market_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Observation */
        get: operations["get_portfolio_observation_api_portfolio_observation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Opportunity
         * @description Scan all active playbooks against current market telemetry.
         *     Returns only eligible candidates (ineligible are hidden per spec).
         *     Portfolio-level gate blocks return an empty list with block_reason set.
         */
        get: operations["scan_opportunity_api_opportunity_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/spec/{playbook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Trade Spec
         * @description Generate a full trade specification for the given playbook.
         *     Runs hard blocks first — if any fire, spec is null and blocks are returned.
         *     Warnings require explicit user confirmation but do not suppress the spec.
         */
        post: operations["get_trade_spec_api_opportunity_spec__playbook_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Position */
        post: operations["close_position_api_positions__position_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/post-mortem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post Mortem */
        get: operations["get_post_mortem_api_positions__position_id__post_mortem_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity Ledger */
        get: operations["get_opportunity_ledger_api_opportunity_ledger_get"];
        put?: never;
        /** Create Opportunity Record */
        post: operations["create_opportunity_record_api_opportunity_ledger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/ledger/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Opportunity Outcome */
        patch: operations["update_opportunity_outcome_api_opportunity_ledger__record_id__patch"];
        trace?: never;
    };
    "/api/performance/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance Diagnostics */
        get: operations["get_performance_diagnostics_api_performance_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountConfig */
        AccountConfig: {
            /** Total Nav */
            total_nav: number;
            /** Broker */
            broker: string;
            /** Account Type */
            account_type: string;
            /** Options Approval */
            options_approval: string;
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "PAPER";
        };
        /** BenchmarkData */
        BenchmarkData: {
            /** Spy Cagr */
            spy_cagr?: number | null;
            /** Bxm Cagr */
            bxm_cagr?: number | null;
            /**
             * Note
             * @default Benchmark data stubbed — live fetch not yet implemented
             */
            note: string;
        };
        /** CandidateCard */
        CandidateCard: {
            playbook: components["schemas"]["PlaybookDefinitionSchema"];
            /** Eligible */
            eligible: boolean;
            /** Suppressed Reason */
            suppressed_reason?: string | null;
            strike_params?: components["schemas"]["StrikeDerivedParams"] | null;
        };
        /** ClosePositionRequest */
        ClosePositionRequest: {
            /** Current Value Per Share */
            current_value_per_share: number;
            /**
             * Exit Trigger
             * @enum {string}
             */
            exit_trigger: "PROFIT_TARGET" | "LOSS_LIMIT" | "TIME_RULE" | "CATALYST_RULE" | "MANUAL";
            /** Actual Underlying Move Pct */
            actual_underlying_move_pct: number;
            /** Lesson Tags */
            lesson_tags?: string[];
        };
        /** ClosurePostMortemSchema */
        ClosurePostMortemSchema: {
            /** Id */
            id: string;
            /** Position Id */
            position_id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "WIN" | "LOSS" | "BREAKEVEN";
            /** Realized Pnl */
            realized_pnl: number;
            /** Actual Underlying Move Pct */
            actual_underlying_move_pct: number;
            /** Exit Date */
            exit_date: string;
            /**
             * Exit Trigger
             * @enum {string}
             */
            exit_trigger: "PROFIT_TARGET" | "LOSS_LIMIT" | "TIME_RULE" | "CATALYST_RULE" | "MANUAL";
            /** Lesson Tags */
            lesson_tags: string[];
            /** User Override Logged */
            user_override_logged: boolean;
            /** Playbook Id */
            playbook_id?: string | null;
            /** Playbook Version */
            playbook_version?: string | null;
        };
        /** EntryFilters */
        EntryFilters: {
            /** Min Ivr */
            min_ivr: number;
            /** Max Ivr */
            max_ivr: number;
            /** Vix Range */
            vix_range: [
                number,
                number
            ];
            /**
             * Required Trend
             * @enum {string}
             */
            required_trend: "ABOVE_SMA20" | "BELOW_SMA20" | "ANY";
            /** Block Catalyst 14Dte */
            block_catalyst_14dte: boolean;
            /** Require Catalyst 14Dte */
            require_catalyst_14dte: boolean;
        };
        /** ExecutionSpecs */
        ExecutionSpecs: {
            /** Target Dte */
            target_dte: number;
            /** Short Leg Delta */
            short_leg_delta: number;
            /** Long Leg Delta */
            long_leg_delta: number;
            /** Spread Width Dollars */
            spread_width_dollars: number;
            /** Straddle Atm */
            straddle_atm: boolean;
        };
        /** ExitRules */
        ExitRules: {
            /** Profit Take Pct */
            profit_take_pct: number;
            /** Stop Loss Pct */
            stop_loss_pct: number;
            /** Mandatory Exit Dte */
            mandatory_exit_dte: number;
            /** Catalyst Exit Days After */
            catalyst_exit_days_after: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardBlock */
        HardBlock: {
            /** Check */
            check: string;
            /** Reason */
            reason: string;
        };
        /** MarketStateSchema */
        MarketStateSchema: {
            /**
             * Current Regime
             * @enum {string}
             */
            current_regime: "CALM_BULL" | "HIGH_VOL_NEUTRAL" | "TRENDING_BEAR" | "EVENT_CATALYST";
            /** Spy Price */
            spy_price: number;
            /**
             * Spy Sma20
             * @default 0
             */
            spy_sma20: number;
            /**
             * Vix Close
             * @default 0
             */
            vix_close: number;
            /** Underlying Ivrs */
            underlying_ivrs?: {
                [key: string]: number;
            };
            /**
             * Spy Daily Return
             * @default 0
             */
            spy_daily_return: number;
            /** Catalyst Dates */
            catalyst_dates?: string[];
            /** Regime Scores */
            regime_scores?: {
                [key: string]: number;
            };
        };
        /** OperationalJournalEntrySchema */
        OperationalJournalEntrySchema: {
            /** Core Thesis Rationale */
            core_thesis_rationale: string;
            /** Structural Invalidation */
            structural_invalidation: string;
            /** Expected Underlying Move Pct */
            expected_underlying_move_pct: number;
            /**
             * Pre Trade Emotional State
             * @enum {string}
             */
            pre_trade_emotional_state: "Calm" | "Anxious" | "Chasing" | "Bored";
            /**
             * Pre Trade Confidence Rating
             * @enum {integer}
             */
            pre_trade_confidence_rating: 1 | 2 | 3 | 4 | 5;
        };
        /** OpportunityRecordSchema */
        OpportunityRecordSchema: {
            /** Id */
            id: string;
            /** Playbook Id */
            playbook_id: string;
            /** Playbook Version */
            playbook_version: string;
            /** Generated At */
            generated_at: string;
            /** Accepted */
            accepted: boolean;
            /** Outcome If Taken */
            outcome_if_taken?: number | null;
            /** Bypass Reason */
            bypass_reason?: string | null;
        };
        /** OpportunityScanResult */
        OpportunityScanResult: {
            /** Portfolio Blocked */
            portfolio_blocked: boolean;
            /** Block Reason */
            block_reason?: string | null;
            /** Candidates */
            candidates: components["schemas"]["CandidateCard"][];
        };
        /** OptionLegSchema */
        OptionLegSchema: {
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Direction
             * @enum {string}
             */
            direction: "LONG" | "SHORT";
            /** Strike */
            strike: number;
            /** Expiration */
            expiration: string;
            /** Delta */
            delta: number;
            /** Theta */
            theta: number;
            /** Vega */
            vega: number;
            /**
             * Gamma
             * @default 0
             */
            gamma: number;
        };
        /** PerformanceDiagnosticsSchema */
        PerformanceDiagnosticsSchema: {
            /** Generated At */
            generated_at: string;
            /** Playbook Metrics */
            playbook_metrics: components["schemas"]["PlaybookMetrics"][];
            benchmarks: components["schemas"]["BenchmarkData"];
        };
        /** PlaybookDefinitionSchema */
        PlaybookDefinitionSchema: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Underlying Ticker */
            underlying_ticker: string;
            /**
             * Strategy Type
             * @enum {string}
             */
            strategy_type: "BULL_CALL_SPREAD" | "BEAR_PUT_SPREAD" | "BULL_PUT_SPREAD" | "BEAR_CALL_SPREAD" | "IRON_CONDOR" | "LONG_STRADDLE" | "LONG_STRANGLE";
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "PAPER";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            entry_filters: components["schemas"]["EntryFilters"];
            execution_specs: components["schemas"]["ExecutionSpecs"];
            exit_rules: components["schemas"]["ExitRules"];
        };
        /** PlaybookMetrics */
        PlaybookMetrics: {
            /** Playbook Id */
            playbook_id: string;
            /** Playbook Version */
            playbook_version: string;
            /** Total Trades */
            total_trades: number;
            /** Win Rate */
            win_rate?: number | null;
            /** Profit Factor */
            profit_factor?: number | null;
            /** Avg Return On Risk */
            avg_return_on_risk?: number | null;
            /**
             * Cagr
             * @default N/A (insufficient data)
             */
            cagr: string;
            /**
             * Max Drawdown
             * @default N/A (insufficient data)
             */
            max_drawdown: string;
            /**
             * Sharpe
             * @default N/A (insufficient data)
             */
            sharpe: string;
        };
        /** PortfolioConfigSchema */
        PortfolioConfigSchema: {
            account: components["schemas"]["AccountConfig"];
            risk_profile: components["schemas"]["RiskProfile"];
            portfolio_greek_limits: components["schemas"]["PortfolioGreekLimits"];
        };
        /** PortfolioGreekLimits */
        PortfolioGreekLimits: {
            /** Max Net Delta */
            max_net_delta: number;
            /** Max Net Vega */
            max_net_vega: number;
            /** Max Net Gamma */
            max_net_gamma: number;
        };
        /** PositionSchema */
        PositionSchema: {
            /** Id */
            id: string;
            /** Underlying */
            underlying: string;
            /**
             * Strategy Type
             * @enum {string}
             */
            strategy_type: "BULL_CALL_SPREAD" | "BEAR_PUT_SPREAD" | "BULL_PUT_SPREAD" | "BEAR_CALL_SPREAD" | "IRON_CONDOR" | "LONG_STRADDLE" | "LONG_STRANGLE";
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "LIVE" | "PAPER";
            /** Legs */
            legs: components["schemas"]["OptionLegSchema"][];
            /** Entry Date */
            entry_date: string;
            /** Expiration Date */
            expiration_date: string;
            /** Entry Premium */
            entry_premium: number;
            /**
             * Premium Direction
             * @enum {string}
             */
            premium_direction: "CREDIT" | "DEBIT";
            /** Current Value Per Share */
            current_value_per_share: number;
            /** Contracts */
            contracts: number;
            /** Max Profit */
            max_profit: number;
            /** Max Loss */
            max_loss: number;
            /** Profit Target Per Share */
            profit_target_per_share?: number | null;
            /** Loss Limit Per Share */
            loss_limit_per_share?: number | null;
            /** Break Even Upside */
            break_even_upside?: number | null;
            /** Break Even Downside */
            break_even_downside?: number | null;
            /** Notes */
            notes: string;
            /**
             * Rolls
             * @default 0
             */
            rolls: number;
            /**
             * Status
             * @enum {string}
             */
            status: "OPEN" | "CLOSED" | "EXPIRED";
            /** Playbook Id */
            playbook_id?: string | null;
            /** Playbook Version */
            playbook_version?: string | null;
            playbook_snapshot?: components["schemas"]["PlaybookDefinitionSchema"] | null;
            journal: components["schemas"]["OperationalJournalEntrySchema"];
            /** Warnings Acknowledged */
            warnings_acknowledged?: string[];
        };
        /** RiskProfile */
        RiskProfile: {
            /** Max Trade Risk Pct */
            max_trade_risk_pct: number;
            /** Max Trade Risk Dollars */
            max_trade_risk_dollars: number;
            /** Max Underlying Concentration Pct */
            max_underlying_concentration_pct: number;
            /** Max Correlated Index Pct */
            max_correlated_index_pct: number;
            /** Minimum Cash Reserve Pct */
            minimum_cash_reserve_pct: number;
            /** Max Simultaneous Positions */
            max_simultaneous_positions: number;
            /** Max Capital Deployed Pct */
            max_capital_deployed_pct: number;
        };
        /**
         * StrikeDerivedParams
         * @description Documents how strikes were derived so every output is traceable.
         */
        StrikeDerivedParams: {
            /** Underlying */
            underlying: string;
            /** Current Price */
            current_price: number;
            /** Target Dte */
            target_dte: number;
            /** Short Leg Delta */
            short_leg_delta?: number | null;
            /** Long Leg Delta */
            long_leg_delta?: number | null;
            /** Spread Width Dollars */
            spread_width_dollars?: number | null;
            /** One Sigma Move */
            one_sigma_move?: number | null;
            /** Derivation Note */
            derivation_note: string;
        };
        /** TradeSpec */
        TradeSpec: {
            /** Playbook Id */
            playbook_id: string;
            /** Playbook Name */
            playbook_name: string;
            /** Underlying */
            underlying: string;
            /** Strategy Type */
            strategy_type: string;
            /** Legs */
            legs: components["schemas"]["TradeSpecLeg"][];
            /** Expiration Date */
            expiration_date: string;
            /** Dte At Entry */
            dte_at_entry: number;
            /**
             * Order Type
             * @default LIMIT
             * @constant
             */
            order_type: "LIMIT";
            /** Limit Price Per Share */
            limit_price_per_share: number;
            /** Max Loss Dollars */
            max_loss_dollars: number;
            /** Max Gain Dollars */
            max_gain_dollars?: number | null;
            /** Max Gain Note */
            max_gain_note: string;
            /** Break Even Prices */
            break_even_prices: number[];
            /** Profit Target Dollars */
            profit_target_dollars: number;
            /** Profit Target Pct */
            profit_target_pct: number;
            /** Loss Limit Dollars */
            loss_limit_dollars: number;
            /** Loss Limit Pct */
            loss_limit_pct: number;
            /** Closing Order Instructions */
            closing_order_instructions: string;
            derivation_params: components["schemas"]["StrikeDerivedParams"];
        };
        /** TradeSpecLeg */
        TradeSpecLeg: {
            /**
             * Action
             * @enum {string}
             */
            action: "BUY" | "SELL";
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /** Strike */
            strike: number;
            /** Expiration Date */
            expiration_date: string;
            /** Quantity */
            quantity: number;
            /** Delta Target */
            delta_target?: number | null;
        };
        /** TradeSpecResult */
        TradeSpecResult: {
            /** Hard Blocks */
            hard_blocks: components["schemas"]["HardBlock"][];
            /** Warnings */
            warnings: components["schemas"]["TradeWarning"][];
            spec?: components["schemas"]["TradeSpec"] | null;
        };
        /** TradeWarning */
        TradeWarning: {
            /** Check */
            check: string;
            /** Message */
            message: string;
        };
        /** UpdateOutcomeRequest */
        UpdateOutcomeRequest: {
            /** Outcome If Taken */
            outcome_if_taken: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_portfolio_config_api_portfolio_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioConfigSchema"];
                };
            };
        };
    };
    update_portfolio_config_api_portfolio_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioConfigSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioConfigSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_positions_api_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"][];
                };
            };
        };
    };
    create_position_api_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_position_prices_api_positions_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"][];
                };
            };
        };
    };
    get_post_mortems_api_positions_post_mortems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosurePostMortemSchema"][];
                };
            };
        };
    };
    get_position_api_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playbooks_api_playbooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookDefinitionSchema"][];
                };
            };
        };
    };
    create_playbook_api_playbooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaybookDefinitionSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookDefinitionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_state_api_market_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
        };
    };
    update_market_state_api_market_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketStateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_live_market_state_api_market_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
        };
    };
    get_portfolio_observation_api_portfolio_observation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    scan_opportunity_api_opportunity_scan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityScanResult"];
                };
            };
        };
    };
    get_trade_spec_api_opportunity_spec__playbook_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playbook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeSpecResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_position_api_positions__position_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosePositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosurePostMortemSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_mortem_api_positions__position_id__post_mortem_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosurePostMortemSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_ledger_api_opportunity_ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRecordSchema"][];
                };
            };
        };
    };
    create_opportunity_record_api_opportunity_ledger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityRecordSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRecordSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_opportunity_outcome_api_opportunity_ledger__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRecordSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_performance_diagnostics_api_performance_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceDiagnosticsSchema"];
                };
            };
        };
    };
}
