/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Config */
        get: operations["get_portfolio_config_api_portfolio_config_get"];
        put?: never;
        /** Update Portfolio Config */
        post: operations["update_portfolio_config_api_portfolio_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_api_positions_get"];
        put?: never;
        /** Create Position */
        post: operations["create_position_api_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Position Prices
         * @description Reprice open positions from IB Gateway quotes (the operator's nightly
         *     repricer, shared) and return the full position list.
         */
        post: operations["refresh_position_prices_api_positions_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/post-mortems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post Mortems */
        get: operations["get_post_mortems_api_positions_post_mortems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_positions__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playbooks */
        get: operations["get_playbooks_api_playbooks_get"];
        put?: never;
        /** Create Playbook */
        post: operations["create_playbook_api_playbooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market State */
        get: operations["get_market_state_api_market_state_get"];
        put?: never;
        /**
         * Update Market State
         * @description Manually set all telemetry inputs. Regime is recomputed from the provided values.
         */
        post: operations["update_market_state_api_market_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Live Market State
         * @description Triggers a live fetch from IB Gateway for SPY price/SMA20/return and VIX.
         *     Recomputes and saves the regime. Returns 503 if the Gateway is unreachable
         *     or the fetch fails.
         */
        post: operations["fetch_live_market_state_api_market_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Observation */
        get: operations["get_portfolio_observation_api_portfolio_observation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Opportunity
         * @description Scan all active playbooks against current market telemetry.
         *     Returns only eligible candidates (ineligible are hidden per spec).
         *     Portfolio-level gate blocks return an empty list with block_reason set.
         */
        get: operations["scan_opportunity_api_opportunity_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/spec/{playbook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Trade Spec
         * @description Generate a full trade specification for the given playbook.
         *     Runs hard blocks first — if any fire, spec is null and blocks are returned.
         *     Warnings require explicit user confirmation but do not suppress the spec.
         */
        post: operations["get_trade_spec_api_opportunity_spec__playbook_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Position */
        post: operations["close_position_api_positions__position_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll Position
         * @description Execute a defensive roll (domain-rules.md): net-credit only, max 2 rolls,
         *     down-and-out for puts / up-and-out for calls. Debit rolls are blocked —
         *     the correct action there is taking the loss.
         */
        post: operations["roll_position_api_positions__position_id__roll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/post-mortem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post Mortem */
        get: operations["get_post_mortem_api_positions__position_id__post_mortem_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity Ledger */
        get: operations["get_opportunity_ledger_api_opportunity_ledger_get"];
        put?: never;
        /** Create Opportunity Record */
        post: operations["create_opportunity_record_api_opportunity_ledger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunity/ledger/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Opportunity Outcome */
        patch: operations["update_opportunity_outcome_api_opportunity_ledger__record_id__patch"];
        trace?: never;
    };
    "/api/performance/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Performance Diagnostics */
        get: operations["get_performance_diagnostics_api_performance_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trading-control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trading Control */
        get: operations["get_trading_control_api_trading_control_get"];
        put?: never;
        /**
         * Update Trading Control
         * @description The console control surface — the ONLY place RESUME exists (ADR-0008).
         */
        post: operations["update_trading_control_api_trading_control_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Books
         * @description Per-book summaries with the ADR-0006 Live Gate checklist (Books tab).
         */
        get: operations["get_books_api_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Events
         * @description The append-only audit trail, newest first. `date` prefix-matches run_at
         *     (e.g. '2026-08' for a month, '2026-08-18' for a day). `event_type`
         *     substring-matches, case-insensitively (#479) — exact match made "reject"
         *     silently return nothing instead of REJECTED/ORDER_REJECTED/etc, which
         *     read as "no such events" rather than "wrong filter".
         */
        get: operations["get_audit_events_api_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executor/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Executor Status
         * @description Heartbeat + last reconciliation for the status strip.
         */
        get: operations["get_executor_status_api_executor_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live Orders
         * @description What the system currently believes is resting at the broker (#601) —
         *     ref, book, plain-English spread label, order type/TIF/status — so an
         *     operator can directly compare against the IBKR app during an incident
         *     instead of reconstructing it from audit rows.
         */
        get: operations["get_live_orders_api_orders_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Reconciliation */
        get: operations["get_latest_reconciliation_api_reconciliation_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation/{run_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Reconciliation Run
         * @description Record the human explanation on a drift run. Never auto-resumes (ADR-0008).
         */
        post: operations["resolve_reconciliation_run_api_reconciliation__run_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolution/external-close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolution External Close
         * @description 'This position was closed at the broker' — CLOSED at the stated value,
         *     cash moved, MANUAL post-mortem, everything audited as actor=resolution.
         */
        post: operations["resolution_external_close_api_resolution_external_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolution/partial-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolution Partial Order
         * @description Terminalize a PARTIAL order row (#414) — releases its encumbrance and
         *     slot. Record the partial's cash/position consequences FIRST (external
         *     close / cash adjust); this only clears the latch.
         */
        post: operations["resolution_partial_order_api_resolution_partial_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolution/cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolution Cash Adjustment
         * @description A signed cash correction with a mandatory reason (audited).
         */
        post: operations["resolution_cash_adjustment_api_resolution_cash_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolution/flex-ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolution Flex Ack
         * @description Explain a weekly Flex-audit discrepancy exec_id once (#544) — the
         *     corrected books stop re-alerting it at urgent priority forever.
         */
        post: operations["resolution_flex_ack_api_resolution_flex_ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/fill-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fill Quality
         * @description Measured slippage vs the decided mid, decomposed into ladder
         *     concession and market movement, against the $5/contract haircut.
         */
        get: operations["get_fill_quality_api_analysis_fill_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Books ranked by expectancy after haircut, plus the knob sweeps —
         *     verdicts only speak once every point has a minimum sample.
         */
        get: operations["get_leaderboard_api_analysis_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/regime-hit-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regime Hit Rate
         * @description Entry-day regime vs closed outcome — the observational complement to
         *     the B12 no-gate control arm.
         */
        get: operations["get_regime_hit_rate_api_analysis_regime_hit_rate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountConfig */
        AccountConfig: {
            /** Total Nav */
            total_nav: number;
            /** Broker */
            broker: string;
            /** Account Type */
            account_type: string;
            /** Options Approval */
            options_approval: string;
        };
        /** AuditEventSchema */
        AuditEventSchema: {
            /** Id */
            id: number;
            /** Run At */
            run_at: string;
            /** Book Id */
            book_id: string | null;
            /** Event Type */
            event_type: string;
            /** Actor */
            actor: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Urgent */
            urgent: boolean;
            /** Book Label */
            book_label?: string | null;
        };
        /** BenchmarkData */
        BenchmarkData: {
            /** Spy Cagr */
            spy_cagr?: number | null;
            /** Bxm Cagr */
            bxm_cagr?: number | null;
            /**
             * Note
             * @default No benchmark data available
             */
            note: string;
        };
        /** BookSummarySchema */
        BookSummarySchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Engine Variant */
            engine_variant: string;
            /** Underlying */
            underlying: string;
            /** Config Hash */
            config_hash: string;
            /** Config Version */
            config_version: number;
            /** Starting Capital */
            starting_capital: number;
            /** Cash Balance */
            cash_balance: number;
            /** Last Mtm */
            last_mtm: number | null;
            /** Pnl */
            pnl: number;
            /** Closed Trades */
            closed_trades: number;
            /** Win Rate */
            win_rate: number | null;
            /** Expectancy After Haircut */
            expectancy_after_haircut: number | null;
            /** Max Drawdown */
            max_drawdown: number;
            /** Deployed Pct */
            deployed_pct: number;
            /** Open Positions */
            open_positions: number;
            /** Max Positions */
            max_positions: number;
            /**
             * Control State
             * @enum {string}
             */
            control_state: "ACTIVE" | "HALT_ENTRIES" | "FLATTEN_REQUESTED";
            live_gate: components["schemas"]["LiveGateChecklistSchema"];
        };
        /** BooksView */
        BooksView: {
            /** Books */
            books: components["schemas"]["BookSummarySchema"][];
        };
        /** CandidateCard */
        CandidateCard: {
            playbook: components["schemas"]["PlaybookDefinitionSchema"];
            /** Eligible */
            eligible: boolean;
            /** Suppressed Reason */
            suppressed_reason?: string | null;
            strike_params?: components["schemas"]["StrikeDerivedParams"] | null;
        };
        /**
         * CashAdjustmentRequest
         * @description Resolution flow (#310): a signed cash correction with a reason.
         */
        CashAdjustmentRequest: {
            /** Book Id */
            book_id: string;
            /** Delta */
            delta: number;
            /** Reason */
            reason: string;
        };
        /** CashAdjustmentResult */
        CashAdjustmentResult: {
            /** Book Id */
            book_id: string;
            /** Cash Balance */
            cash_balance: number;
        };
        /** ClosePositionRequest */
        ClosePositionRequest: {
            /** Current Value Per Share */
            current_value_per_share: number;
            /**
             * Exit Trigger
             * @enum {string}
             */
            exit_trigger: "PROFIT_TARGET" | "LOSS_LIMIT" | "TIME_RULE" | "CATALYST_RULE" | "MANUAL" | "REGIME_FLIP" | "ASSIGNMENT_RISK" | "EXPIRY";
            /** Actual Underlying Move Pct */
            actual_underlying_move_pct: number;
            /** Lesson Tags */
            lesson_tags?: string[];
            /**
             * Acknowledge Broker Divergence
             * @default false
             */
            acknowledge_broker_divergence: boolean;
            /**
             * Acknowledge Cancelled
             * @default false
             */
            acknowledge_cancelled: boolean;
        };
        /** ClosurePostMortemSchema */
        ClosurePostMortemSchema: {
            /** Id */
            id: string;
            /** Position Id */
            position_id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "WIN" | "LOSS" | "BREAKEVEN";
            /** Realized Pnl */
            realized_pnl: number;
            /** Actual Underlying Move Pct */
            actual_underlying_move_pct: number;
            /** Exit Date */
            exit_date: string;
            /**
             * Exit Trigger
             * @enum {string}
             */
            exit_trigger: "PROFIT_TARGET" | "LOSS_LIMIT" | "TIME_RULE" | "CATALYST_RULE" | "MANUAL" | "REGIME_FLIP" | "ASSIGNMENT_RISK" | "EXPIRY";
            /** Lesson Tags */
            lesson_tags: string[];
            /** User Override Logged */
            user_override_logged: boolean;
            /** Playbook Id */
            playbook_id?: string | null;
            /** Playbook Version */
            playbook_version?: string | null;
        };
        /** EntryFilters */
        EntryFilters: {
            /** Min Ivr */
            min_ivr: number;
            /** Max Ivr */
            max_ivr: number;
            /** Vix Range */
            vix_range: [
                number,
                number
            ];
            /**
             * Required Trend
             * @enum {string}
             */
            required_trend: "ABOVE_SMA20" | "BELOW_SMA20" | "ANY";
            /** Block Catalyst 14Dte */
            block_catalyst_14dte: boolean;
            /** Require Catalyst 14Dte */
            require_catalyst_14dte: boolean;
            /**
             * Require Scoped Catalyst
             * @default false
             */
            require_scoped_catalyst: boolean;
        };
        /** ExecutionSpecs */
        ExecutionSpecs: {
            /** Target Dte */
            target_dte: number;
            /** Short Leg Delta */
            short_leg_delta: number;
            /** Long Leg Delta */
            long_leg_delta: number;
            /** Spread Width Dollars */
            spread_width_dollars: number;
            /** Straddle Atm */
            straddle_atm: boolean;
        };
        /** ExecutorStatusSchema */
        ExecutorStatusSchema: {
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Heartbeat Age Hours */
            heartbeat_age_hours: number | null;
            /** Stale */
            stale: boolean;
            /** Broker Ok */
            broker_ok: boolean | null;
            /** Entries Placed */
            entries_placed: number | null;
            /** Closes Placed */
            closes_placed: number | null;
            /** Last Reconciliation At */
            last_reconciliation_at: string | null;
            /** Last Reconciliation Result */
            last_reconciliation_result: string | null;
            /** Last Reconciliation Resolved */
            last_reconciliation_resolved?: boolean | null;
            /** Last Digest At */
            last_digest_at?: string | null;
            /** Last Digest Pushed */
            last_digest_pushed?: boolean | null;
            /** Last Urgent Pushed */
            last_urgent_pushed?: boolean | null;
            /**
             * Trading Mode
             * @default paper
             * @enum {string}
             */
            trading_mode: "paper" | "live";
        };
        /** ExitRules */
        ExitRules: {
            /** Profit Take Pct */
            profit_take_pct: number;
            /** Stop Loss Pct */
            stop_loss_pct: number;
            /** Mandatory Exit Dte */
            mandatory_exit_dte: number;
        };
        /**
         * ExternalCloseRequest
         * @description Resolution flow (#310): 'this position was closed at the broker'.
         */
        ExternalCloseRequest: {
            /** Position Id */
            position_id: string;
            /** Exit Value Per Share */
            exit_value_per_share: number;
            /** Reason */
            reason: string;
            /**
             * Acknowledge Cancelled
             * @default false
             */
            acknowledge_cancelled: boolean;
        };
        /** FillQualityAggregate */
        FillQualityAggregate: {
            /** Label */
            label: string;
            /** Orders */
            orders: number;
            /** Contracts */
            contracts: number;
            /** Avg Slippage Per Contract */
            avg_slippage_per_contract?: number | null;
            /** Total Commissions */
            total_commissions: number;
        };
        /** FillQualityReport */
        FillQualityReport: {
            /** Generated At */
            generated_at: string;
            /** Orders Analyzed */
            orders_analyzed: number;
            /** Orders Awaiting Fills */
            orders_awaiting_fills: number;
            /** Haircut Per Contract */
            haircut_per_contract: number;
            /** Avg Slippage Per Contract */
            avg_slippage_per_contract?: number | null;
            /** Total Commissions */
            total_commissions: number;
            /** By Book */
            by_book: components["schemas"]["FillQualityAggregate"][];
            /** By Action */
            by_action: components["schemas"]["FillQualityAggregate"][];
            /** Rows */
            rows: components["schemas"]["FillQualityRow"][];
        };
        /**
         * FillQualityRow
         * @description One filled order's execution quality (#242). Per-share values are
         *     signed like order rows (negative = credit); slippage values are oriented
         *     so positive = worse than the decided mid.
         */
        FillQualityRow: {
            /** Order Ref */
            order_ref: string;
            /** Book Id */
            book_id: string;
            /** Action */
            action: string;
            /** Underlying */
            underlying: string;
            /** Contracts */
            contracts: number;
            /** Decision Midpoint */
            decision_midpoint: number;
            /** Limit Price */
            limit_price: number;
            /** Net Fill Per Share */
            net_fill_per_share?: number | null;
            /** Ladder Concession Per Share */
            ladder_concession_per_share: number;
            /** Market Slippage Per Share */
            market_slippage_per_share?: number | null;
            /** Total Slippage Per Share */
            total_slippage_per_share?: number | null;
            /** Commissions */
            commissions: number;
        };
        /**
         * FlexAckRequest
         * @description Resolution flow (#544): explain a Flex-audit discrepancy exec_id once
         *     so the weekly audit stops re-alerting a correction already made.
         */
        FlexAckRequest: {
            /** Exec Ids */
            exec_ids: string[];
            /** Reason */
            reason: string;
        };
        /** FlexAckResult */
        FlexAckResult: {
            /** Acked */
            acked: string[];
            /** Already Acked */
            already_acked: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardBlock */
        HardBlock: {
            /** Check */
            check: string;
            /** Reason */
            reason: string;
        };
        /**
         * KnobPointSchema
         * @description One book's reading along a swept knob dimension (#243).
         */
        KnobPointSchema: {
            /** Book Id */
            book_id: string;
            /** Knob Value */
            knob_value: string;
            /** Expectancy After Haircut */
            expectancy_after_haircut?: number | null;
            /** Closed Trades */
            closed_trades: number;
        };
        /** KnobSweepSchema */
        KnobSweepSchema: {
            /** Dimension */
            dimension: string;
            /** Points */
            points: components["schemas"]["KnobPointSchema"][];
            /** Verdict */
            verdict: string;
        };
        /** LeaderboardReport */
        LeaderboardReport: {
            /** Generated At */
            generated_at: string;
            /** Min Trades Per Point */
            min_trades_per_point: number;
            /** Ranked */
            ranked: components["schemas"]["BookSummarySchema"][];
            /** Sweeps */
            sweeps: components["schemas"]["KnobSweepSchema"][];
        };
        /**
         * LiveGateChecklistSchema
         * @description ADR-0006 Live Gate criteria, each with its current value and pass flag.
         */
        LiveGateChecklistSchema: {
            /** Closed Trades */
            closed_trades: number;
            /** Closed Trades Required */
            closed_trades_required: number;
            /** Trades Ok */
            trades_ok: boolean;
            /** Months Elapsed */
            months_elapsed: number;
            /** Months Required */
            months_required: number;
            /** Months Ok */
            months_ok: boolean;
            /** Breaches */
            breaches: number;
            /** Breaches Ok */
            breaches_ok: boolean;
            /** Expectancy After Haircut */
            expectancy_after_haircut: number | null;
            /** Expectancy Ok */
            expectancy_ok: boolean;
            /** Eligible */
            eligible: boolean;
        };
        /**
         * LiveOrderSchema
         * @description A resting-at-broker order for the console's live-order panel (#601) —
         *     lets an operator directly compare against the IBKR app during an
         *     incident instead of reconstructing it from audit rows. Only orders in a
         *     non-terminal status (STAGED/SUBMITTED/PARTIAL) are ever returned.
         */
        LiveOrderSchema: {
            /** Order Ref */
            order_ref: string;
            /** Book Id */
            book_id: string;
            /** Label */
            label: string;
            /** Order Type */
            order_type: string;
            /**
             * Tif
             * @enum {string}
             */
            tif: "DAY" | "GTC";
            /**
             * Status
             * @enum {string}
             */
            status: "STAGED" | "SUBMITTED" | "PARTIAL";
            /** Submitted At */
            submitted_at: string | null;
        };
        /** MarketStateSchema */
        MarketStateSchema: {
            /**
             * Current Regime
             * @enum {string}
             */
            current_regime: "CALM_BULL" | "HIGH_VOL_NEUTRAL" | "TRENDING_BEAR" | "EVENT_CATALYST";
            /** Spy Price */
            spy_price: number;
            /**
             * Spy Sma20
             * @default 0
             */
            spy_sma20: number;
            /**
             * Vix Close
             * @default 0
             */
            vix_close: number;
            /** Underlying Ivrs */
            underlying_ivrs?: {
                [key: string]: number;
            };
            /**
             * Spy Daily Return
             * @default 0
             */
            spy_daily_return: number;
            /** Catalyst Dates */
            catalyst_dates?: string[];
            /** Regime Scores */
            regime_scores?: {
                [key: string]: number;
            };
            /** Underlying Prices */
            underlying_prices?: {
                [key: string]: number;
            };
            /** Underlying Sma20 */
            underlying_sma20?: {
                [key: string]: number;
            };
        };
        /** OperationalJournalEntrySchema */
        OperationalJournalEntrySchema: {
            /** Core Thesis Rationale */
            core_thesis_rationale: string;
            /** Structural Invalidation */
            structural_invalidation: string;
            /** Expected Underlying Move Pct */
            expected_underlying_move_pct: number;
            /**
             * Pre Trade Emotional State
             * @enum {string}
             */
            pre_trade_emotional_state: "Calm" | "Anxious" | "Chasing" | "Bored";
            /**
             * Pre Trade Confidence Rating
             * @enum {integer}
             */
            pre_trade_confidence_rating: 1 | 2 | 3 | 4 | 5;
        };
        /** OpportunityRecordSchema */
        OpportunityRecordSchema: {
            /** Id */
            id: string;
            /** Playbook Id */
            playbook_id: string;
            /** Playbook Version */
            playbook_version: string;
            /** Generated At */
            generated_at: string;
            /** Accepted */
            accepted: boolean;
            /** Outcome If Taken */
            outcome_if_taken?: number | null;
            /** Bypass Reason */
            bypass_reason?: string | null;
        };
        /** OpportunityScanResult */
        OpportunityScanResult: {
            /** Portfolio Blocked */
            portfolio_blocked: boolean;
            /** Block Reason */
            block_reason?: string | null;
            /** Candidates */
            candidates: components["schemas"]["CandidateCard"][];
        };
        /** OptionLegSchema */
        OptionLegSchema: {
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Direction
             * @enum {string}
             */
            direction: "LONG" | "SHORT";
            /** Strike */
            strike: number;
            /** Expiration */
            expiration: string;
            /** Delta */
            delta: number;
            /** Theta */
            theta: number;
            /** Vega */
            vega: number;
            /**
             * Gamma
             * @default 0
             */
            gamma: number;
        };
        /**
         * PartialOrderResolveRequest
         * @description Resolution flow (#414): terminalize a PARTIAL order row, releasing its
         *     encumbrance and slot after the human has recorded the partial's cash and
         *     position consequences.
         */
        PartialOrderResolveRequest: {
            /** Order Ref */
            order_ref: string;
            /** Reason */
            reason: string;
        };
        /** PartialOrderResolveResult */
        PartialOrderResolveResult: {
            /** Order Ref */
            order_ref: string;
            /** Status */
            status: string;
        };
        /** PerformanceDiagnosticsSchema */
        PerformanceDiagnosticsSchema: {
            /** Generated At */
            generated_at: string;
            /** Playbook Metrics */
            playbook_metrics: components["schemas"]["PlaybookMetrics"][];
            benchmarks: components["schemas"]["BenchmarkData"];
        };
        /** PlaybookDefinitionSchema */
        PlaybookDefinitionSchema: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Underlying Ticker */
            underlying_ticker: string;
            /**
             * Strategy Type
             * @enum {string}
             */
            strategy_type: "BULL_CALL_SPREAD" | "BEAR_PUT_SPREAD" | "BULL_PUT_SPREAD" | "BEAR_CALL_SPREAD" | "IRON_CONDOR" | "BROKEN_WING_BUTTERFLY" | "CALENDAR_SPREAD" | "LONG_STRADDLE" | "LONG_STRANGLE" | "LONG_PUT";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            entry_filters: components["schemas"]["EntryFilters"];
            execution_specs: components["schemas"]["ExecutionSpecs"];
            exit_rules: components["schemas"]["ExitRules"];
        };
        /** PlaybookMetrics */
        PlaybookMetrics: {
            /** Playbook Id */
            playbook_id: string;
            /** Playbook Version */
            playbook_version: string;
            /** Total Trades */
            total_trades: number;
            /** Win Rate */
            win_rate?: number | null;
            /** Profit Factor */
            profit_factor?: number | null;
            /** Avg Return On Risk */
            avg_return_on_risk?: number | null;
            /** Cagr */
            cagr?: number | null;
            /** Max Drawdown */
            max_drawdown?: number | null;
            /** Sharpe */
            sharpe?: number | null;
        };
        /** PortfolioConfigSchema */
        PortfolioConfigSchema: {
            account: components["schemas"]["AccountConfig"];
            risk_profile: components["schemas"]["RiskProfile"];
            portfolio_greek_limits: components["schemas"]["PortfolioGreekLimits"];
        };
        /** PortfolioGreekLimits */
        PortfolioGreekLimits: {
            /** Max Net Delta */
            max_net_delta: number;
            /** Max Net Vega */
            max_net_vega: number;
            /** Max Net Gamma */
            max_net_gamma: number;
        };
        /** PortfolioGreeksSchema */
        PortfolioGreeksSchema: {
            /** Net Delta */
            net_delta: number;
            /** Net Theta */
            net_theta: number;
            /** Net Vega */
            net_vega: number;
            /** Net Gamma */
            net_gamma: number;
        };
        /**
         * PortfolioObservationSchema
         * @description Response contract for GET /api/portfolio/observation.
         */
        PortfolioObservationSchema: {
            /** Scanned Positions */
            scanned_positions: components["schemas"]["ScannedPositionSchema"][];
            greeks: components["schemas"]["PortfolioGreeksSchema"];
            /** Safeguards */
            safeguards: components["schemas"]["SafeguardWarningSchema"][];
            market_state: components["schemas"]["MarketStateSchema"];
        };
        /** PositionSchema */
        PositionSchema: {
            /** Id */
            id: string;
            /** Underlying */
            underlying: string;
            /**
             * Strategy Type
             * @enum {string}
             */
            strategy_type: "BULL_CALL_SPREAD" | "BEAR_PUT_SPREAD" | "BULL_PUT_SPREAD" | "BEAR_CALL_SPREAD" | "IRON_CONDOR" | "BROKEN_WING_BUTTERFLY" | "CALENDAR_SPREAD" | "LONG_STRADDLE" | "LONG_STRANGLE" | "LONG_PUT";
            /** Legs */
            legs: components["schemas"]["OptionLegSchema"][];
            /** Entry Date */
            entry_date: string;
            /** Expiration Date */
            expiration_date: string;
            /** Entry Premium */
            entry_premium: number;
            /**
             * Premium Direction
             * @enum {string}
             */
            premium_direction: "CREDIT" | "DEBIT";
            /** Current Value Per Share */
            current_value_per_share: number;
            /** Contracts */
            contracts: number;
            /** Max Profit */
            max_profit: number;
            /** Max Loss */
            max_loss: number;
            /** Profit Target Per Share */
            profit_target_per_share?: number | null;
            /** Loss Limit Per Share */
            loss_limit_per_share?: number | null;
            /** Break Even Upside */
            break_even_upside?: number | null;
            /** Break Even Downside */
            break_even_downside?: number | null;
            /** Notes */
            notes: string;
            /**
             * Rolls
             * @default 0
             */
            rolls: number;
            /**
             * Status
             * @enum {string}
             */
            status: "OPEN" | "CLOSED" | "EXPIRED";
            /** Playbook Id */
            playbook_id?: string | null;
            /** Playbook Version */
            playbook_version?: string | null;
            playbook_snapshot?: components["schemas"]["PlaybookDefinitionSchema"] | null;
            journal: components["schemas"]["OperationalJournalEntrySchema"];
            /** Warnings Acknowledged */
            warnings_acknowledged?: string[];
            /**
             * Book Id
             * @default B00
             */
            book_id: string;
        };
        /** ReconciliationRunSchema */
        ReconciliationRunSchema: {
            /** Id */
            id: number;
            /** Run At */
            run_at: string;
            /** Result */
            result: string;
            /** Drift Details */
            drift_details?: {
                [key: string]: unknown;
            }[] | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolution */
            resolution?: string | null;
        };
        /** RegimeHitRateReport */
        RegimeHitRateReport: {
            /** Generated At */
            generated_at: string;
            /** Closed Trades */
            closed_trades: number;
            /** By Regime */
            by_regime: components["schemas"]["RegimeHitRateRow"][];
            /** By Engine Regime */
            by_engine_regime: components["schemas"]["RegimeHitRateRow"][];
        };
        /**
         * RegimeHitRateRow
         * @description Closed-trade outcomes for one entry-day regime (#244), optionally
         *     split by the engine variant that decided the entry.
         */
        RegimeHitRateRow: {
            /** Regime */
            regime: string;
            /** Engine Variant */
            engine_variant?: string | null;
            /** Closed Trades */
            closed_trades: number;
            /** Wins */
            wins: number;
            /** Win Rate */
            win_rate?: number | null;
            /** Avg Pnl */
            avg_pnl?: number | null;
            /** Total Pnl */
            total_pnl: number;
        };
        /** ResolveRunRequest */
        ResolveRunRequest: {
            /** Resolution */
            resolution: string;
        };
        /** RiskProfile */
        RiskProfile: {
            /** Max Trade Risk Pct */
            max_trade_risk_pct: number;
            /** Max Trade Risk Dollars */
            max_trade_risk_dollars: number;
            /** Max Underlying Concentration Pct */
            max_underlying_concentration_pct: number;
            /** Max Correlated Index Pct */
            max_correlated_index_pct: number;
            /** Minimum Cash Reserve Pct */
            minimum_cash_reserve_pct: number;
            /** Max Simultaneous Positions */
            max_simultaneous_positions: number;
            /** Max Capital Deployed Pct */
            max_capital_deployed_pct: number;
        };
        /**
         * RollCandidateSchema
         * @description Layer A roll assessment for a credit vertical under pressure (domain-rules.md).
         */
        RollCandidateSchema: {
            /** Eligible */
            eligible: boolean;
            /** Reason */
            reason: string;
            /** Rolls Used */
            rolls_used: number;
            /** Rolls Max */
            rolls_max: number;
            /** Suggested Expiration */
            suggested_expiration?: string | null;
            /** Suggested Legs */
            suggested_legs?: components["schemas"]["RollLegSchema"][] | null;
        };
        /** RollLegSchema */
        RollLegSchema: {
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Direction
             * @enum {string}
             */
            direction: "LONG" | "SHORT";
            /** Strike */
            strike: number;
            /** Expiration */
            expiration: string;
        };
        /** RollPositionRequest */
        RollPositionRequest: {
            /** Close Cost Per Share */
            close_cost_per_share: number;
            /** New Credit Per Share */
            new_credit_per_share: number;
            /** New Expiration */
            new_expiration: string;
            /** New Legs */
            new_legs: components["schemas"]["RollLegSchema"][];
        };
        /** SafeguardWarningSchema */
        SafeguardWarningSchema: {
            /** Type */
            type: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "WARNING" | "CRITICAL";
            /** Message */
            message: string;
        };
        /**
         * ScannedPositionSchema
         * @description One open position with its Layer A lifecycle verdict (observation.py).
         */
        ScannedPositionSchema: {
            /** Position Id */
            position_id: string;
            /** Underlying */
            underlying: string;
            /** Strategy Type */
            strategy_type: string;
            /** Contracts */
            contracts: number;
            /** Max Loss */
            max_loss: number;
            /** Max Profit */
            max_profit: number;
            /** Entry Premium */
            entry_premium: number;
            /**
             * Premium Direction
             * @enum {string}
             */
            premium_direction: "CREDIT" | "DEBIT";
            /** Current Value Per Share */
            current_value_per_share: number;
            /** Expiration Date */
            expiration_date: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "P1 — CLOSE NOW" | "P2 — CLOSE SOON" | "P2 — REVIEW" | "P3 — MONITOR" | "OK";
            /** Action */
            action: string;
            /** Reason */
            reason: string;
            /** Math Detail */
            math_detail: string;
            /** Legs */
            legs: components["schemas"]["OptionLegSchema"][];
            roll?: components["schemas"]["RollCandidateSchema"] | null;
            /**
             * Close In Flight
             * @default false
             */
            close_in_flight: boolean;
            /** Close In Flight Since */
            close_in_flight_since?: string | null;
        };
        /**
         * StrikeDerivedParams
         * @description Documents how strikes were derived so every output is traceable.
         */
        StrikeDerivedParams: {
            /** Underlying */
            underlying: string;
            /** Current Price */
            current_price: number;
            /** Target Dte */
            target_dte: number;
            /** Short Leg Delta */
            short_leg_delta?: number | null;
            /** Long Leg Delta */
            long_leg_delta?: number | null;
            /** Spread Width Dollars */
            spread_width_dollars?: number | null;
            /** One Sigma Move */
            one_sigma_move?: number | null;
            /** Derivation Note */
            derivation_note: string;
        };
        /** TradeSpec */
        TradeSpec: {
            /** Playbook Id */
            playbook_id: string;
            /** Playbook Name */
            playbook_name: string;
            /** Underlying */
            underlying: string;
            /** Strategy Type */
            strategy_type: string;
            /** Legs */
            legs: components["schemas"]["TradeSpecLeg"][];
            /** Expiration Date */
            expiration_date: string;
            /** Dte At Entry */
            dte_at_entry: number;
            /**
             * Order Type
             * @default LIMIT
             * @constant
             */
            order_type: "LIMIT";
            /** Limit Price Per Share */
            limit_price_per_share: number;
            /**
             * Premium Direction
             * @enum {string}
             */
            premium_direction: "CREDIT" | "DEBIT";
            /** Max Loss Dollars */
            max_loss_dollars: number;
            /** Max Gain Dollars */
            max_gain_dollars?: number | null;
            /** Max Gain Note */
            max_gain_note: string;
            /** Break Even Prices */
            break_even_prices: number[];
            /** Profit Target Dollars */
            profit_target_dollars: number;
            /** Profit Target Pct */
            profit_target_pct: number;
            /** Loss Limit Dollars */
            loss_limit_dollars: number;
            /** Loss Limit Pct */
            loss_limit_pct: number;
            /** Closing Order Instructions */
            closing_order_instructions: string;
            derivation_params: components["schemas"]["StrikeDerivedParams"];
        };
        /** TradeSpecLeg */
        TradeSpecLeg: {
            /**
             * Action
             * @enum {string}
             */
            action: "BUY" | "SELL";
            /**
             * Option Type
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /** Strike */
            strike: number;
            /** Expiration Date */
            expiration_date: string;
            /** Quantity */
            quantity: number;
            /** Delta Target */
            delta_target?: number | null;
        };
        /** TradeSpecResult */
        TradeSpecResult: {
            /** Hard Blocks */
            hard_blocks: components["schemas"]["HardBlock"][];
            /** Warnings */
            warnings: components["schemas"]["TradeWarning"][];
            spec?: components["schemas"]["TradeSpec"] | null;
        };
        /** TradeWarning */
        TradeWarning: {
            /** Check */
            check: string;
            /** Message */
            message: string;
        };
        /** TradingControlSchema */
        TradingControlSchema: {
            /** Scope */
            scope: string;
            /**
             * State
             * @enum {string}
             */
            state: "ACTIVE" | "HALT_ENTRIES" | "FLATTEN_REQUESTED";
            /** Reason */
            reason: string;
            /** Actor */
            actor: string;
            /** Changed At */
            changed_at: string;
        };
        /** TradingControlUpdateRequest */
        TradingControlUpdateRequest: {
            /** Scope */
            scope: string;
            /**
             * State
             * @enum {string}
             */
            state: "ACTIVE" | "HALT_ENTRIES" | "FLATTEN_REQUESTED";
            /** Reason */
            reason: string;
        };
        /** TradingControlView */
        TradingControlView: {
            /** Controls */
            controls: components["schemas"]["TradingControlSchema"][];
            /** Sentinel Halt */
            sentinel_halt: boolean;
        };
        /** UpdateOutcomeRequest */
        UpdateOutcomeRequest: {
            /** Outcome If Taken */
            outcome_if_taken: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_portfolio_config_api_portfolio_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioConfigSchema"];
                };
            };
        };
    };
    update_portfolio_config_api_portfolio_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioConfigSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioConfigSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_positions_api_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"][];
                };
            };
        };
    };
    create_position_api_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_position_prices_api_positions_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"][];
                };
            };
        };
    };
    get_post_mortems_api_positions_post_mortems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosurePostMortemSchema"][];
                };
            };
        };
    };
    get_position_api_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playbooks_api_playbooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookDefinitionSchema"][];
                };
            };
        };
    };
    create_playbook_api_playbooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaybookDefinitionSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookDefinitionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_state_api_market_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
        };
    };
    update_market_state_api_market_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketStateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_live_market_state_api_market_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStateSchema"];
                };
            };
        };
    };
    get_portfolio_observation_api_portfolio_observation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioObservationSchema"];
                };
            };
        };
    };
    scan_opportunity_api_opportunity_scan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityScanResult"];
                };
            };
        };
    };
    get_trade_spec_api_opportunity_spec__playbook_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playbook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeSpecResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_position_api_positions__position_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosePositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosurePostMortemSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roll_position_api_positions__position_id__roll_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollPositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_mortem_api_positions__position_id__post_mortem_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosurePostMortemSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_ledger_api_opportunity_ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRecordSchema"][];
                };
            };
        };
    };
    create_opportunity_record_api_opportunity_ledger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityRecordSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRecordSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_opportunity_outcome_api_opportunity_ledger__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRecordSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_performance_diagnostics_api_performance_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceDiagnosticsSchema"];
                };
            };
        };
    };
    get_trading_control_api_trading_control_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingControlView"];
                };
            };
        };
    };
    update_trading_control_api_trading_control_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradingControlUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingControlView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_books_api_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooksView"];
                };
            };
        };
    };
    get_audit_events_api_audit_events_get: {
        parameters: {
            query?: {
                book_id?: string | null;
                date?: string | null;
                event_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_executor_status_api_executor_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutorStatusSchema"];
                };
            };
        };
    };
    get_live_orders_api_orders_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOrderSchema"][];
                };
            };
        };
    };
    get_latest_reconciliation_api_reconciliation_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationRunSchema"];
                };
            };
        };
    };
    resolve_reconciliation_run_api_reconciliation__run_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationRunSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolution_external_close_api_resolution_external_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalCloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosurePostMortemSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolution_partial_order_api_resolution_partial_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartialOrderResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartialOrderResolveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolution_cash_adjustment_api_resolution_cash_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashAdjustmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashAdjustmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolution_flex_ack_api_resolution_flex_ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlexAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlexAckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fill_quality_api_analysis_fill_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillQualityReport"];
                };
            };
        };
    };
    get_leaderboard_api_analysis_leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardReport"];
                };
            };
        };
    };
    get_regime_hit_rate_api_analysis_regime_hit_rate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeHitRateReport"];
                };
            };
        };
    };
}
