/**
 * API client — generated end to end from the backend.
 *
 * `api-types.ts` is generated by `pixi run sync-types` (openapi-typescript);
 * openapi-fetch consumes its `paths` interface, so every URL, method, path
 * param, query param, and response type below is checked against the backend
 * schema at compile time. A renamed or retyped endpoint fails `svelte-check`
 * instead of failing at runtime. Do not hand-write fetch calls here.
 */
import createClient from 'openapi-fetch';
import type { components, paths } from './api-types';

export type Position = components['schemas']['PositionSchema'];
export type PortfolioConfig = components['schemas']['PortfolioConfigSchema'];
export type PortfolioOverview = components['schemas']['PortfolioOverviewSchema'];
export type PlaybookDefinition = components['schemas']['PlaybookDefinitionSchema'];
export type OptionLeg = components['schemas']['OptionLegSchema'];
export type OperationalJournalEntry = components['schemas']['OperationalJournalEntrySchema'];
export type MarketState = components['schemas']['MarketStateSchema'];

export interface RegimeInfo {
  label: string;
  color: string;
  description: string;
}

export const REGIME_DISPLAY: Record<string, RegimeInfo> = {
  CALM_BULL:        { label: 'CALM BULL',        color: 'emerald', description: 'Bullish trend, low volatility — income strategies favoured' },
  HIGH_VOL_NEUTRAL: { label: 'HIGH VOL NEUTRAL', color: 'amber',   description: 'Range-bound, elevated volatility — Iron Condors, CSPs' },
  TRENDING_BEAR:    { label: 'TRENDING BEAR',    color: 'rose',    description: 'Bearish trend — reduce risk, avoid new income positions' },
  EVENT_CATALYST:   { label: 'EVENT CATALYST',   color: 'violet',  description: 'Upcoming catalyst — long volatility strategies only' },
};

export type ScannedPosition = components['schemas']['ScannedPositionSchema'];
export type PortfolioGreeks = components['schemas']['PortfolioGreeksSchema'];
export type SafeguardWarning = components['schemas']['SafeguardWarningSchema'];
export type PortfolioObservation = components['schemas']['PortfolioObservationSchema'];

// Same-origin in the browser (the Vite proxy handles /api in dev); the
// localhost fallback exists because Node's Request rejects relative URLs,
// which would break the vitest suite.
const client = createClient<paths>({
  baseUrl: typeof location !== 'undefined' ? location.origin : 'http://localhost',
  // Late-bind fetch so test spies on globalThis.fetch are honored — the
  // default captures the fetch reference once at client creation.
  fetch: (request) => globalThis.fetch(request),
});

/** A FastAPI 422 validation-error item: `{loc: ["body", "field"], msg: "...", type: "..."}`. */
interface ValidationErrorItem {
  loc?: unknown;
  msg?: unknown;
}

function isValidationErrorItem(item: unknown): item is ValidationErrorItem {
  return typeof item === 'object' && item !== null && 'msg' in item;
}

/** "body -> reason -> field: message" style, skipping the generic "body" loc segment. */
function formatValidationError(item: ValidationErrorItem): string {
  const loc = Array.isArray(item.loc) ? item.loc.filter((seg) => seg !== 'body').join('.') : '';
  const msg = typeof item.msg === 'string' ? item.msg : 'invalid value';
  return loc ? `${loc}: ${msg}` : msg;
}

/** Throw a readable Error when a call fails; FastAPI puts the reason in
 * `detail` — a string for most errors, but an ARRAY of {loc, msg} items for
 * 422 validation errors (#479). Flattening only the string case collapsed
 * every validation failure into an uninformative "Failed to …". */
function unwrap<T>(result: { data?: T; error?: unknown }, action: string): T {
  if (result.error !== undefined || result.data === undefined) {
    const detail = (result.error as { detail?: unknown } | undefined)?.detail;
    if (typeof detail === 'string') {
      throw new Error(detail);
    }
    if (Array.isArray(detail) && detail.length > 0 && detail.every(isValidationErrorItem)) {
      throw new Error(detail.map(formatValidationError).join('; '));
    }
    throw new Error(`Failed to ${action}`);
  }
  return result.data;
}

// openapi-fetch pipes response data through its `Readable<T>` mapped type,
// whose array branch rebuilds tuples as plain arrays — flattening
// EntryFilters.vix_range from [number, number] to number[]. Payloads that
// carry playbook data therefore no longer satisfy the `components` schema
// types, though the runtime data is identical. Cast those back explicitly.
function restoreTuples<T>(data: unknown): T {
  return data as T;
}

export async function getPortfolioConfig(): Promise<PortfolioConfig> {
  return unwrap(await client.GET('/api/portfolio/config'), 'fetch portfolio config');
}

export async function getPortfolioOverview(): Promise<PortfolioOverview> {
  return unwrap(await client.GET('/api/portfolio/overview'), 'fetch portfolio overview');
}

export async function updatePortfolioConfig(config: PortfolioConfig): Promise<PortfolioConfig> {
  return unwrap(await client.POST('/api/portfolio/config', { body: config }), 'update portfolio config');
}

export async function getPositions(): Promise<Position[]> {
  return restoreTuples(unwrap(await client.GET('/api/positions'), 'fetch positions'));
}

export async function getPosition(id: string): Promise<Position> {
  return restoreTuples(
    unwrap(
      await client.GET('/api/positions/{position_id}', { params: { path: { position_id: id } } }),
      'fetch position',
    ),
  );
}

export async function createPosition(pos: Position): Promise<Position> {
  return restoreTuples(unwrap(await client.POST('/api/positions', { body: pos }), 'create position'));
}

export async function getPlaybooks(): Promise<PlaybookDefinition[]> {
  return restoreTuples(unwrap(await client.GET('/api/playbooks'), 'fetch playbooks'));
}

export async function createPlaybook(pb: PlaybookDefinition): Promise<PlaybookDefinition> {
  return restoreTuples(unwrap(await client.POST('/api/playbooks', { body: pb }), 'create playbook'));
}

export async function getMarketState(): Promise<MarketState> {
  return unwrap(await client.GET('/api/market/state'), 'fetch market state');
}

export async function updateMarketState(state: MarketState): Promise<MarketState> {
  return unwrap(await client.POST('/api/market/state', { body: state }), 'update market state');
}

export async function getPortfolioObservation(): Promise<PortfolioObservation> {
  return unwrap(await client.GET('/api/portfolio/observation'), 'fetch portfolio observation');
}

export async function fetchLiveMarketData(): Promise<MarketState> {
  return unwrap(await client.POST('/api/market/fetch'), 'fetch live market data');
}

// ---- Sprint 4: Layer C types ----

export type StrikeDerivedParams = components['schemas']['StrikeDerivedParams'];
export type CandidateCard = components['schemas']['CandidateCard'];
export type OpportunityScanResult = components['schemas']['OpportunityScanResult'];
export type TradeSpecLeg = components['schemas']['TradeSpecLeg'];
export type TradeSpec = components['schemas']['TradeSpec'];
export type HardBlock = components['schemas']['HardBlock'];
export type TradeWarning = components['schemas']['TradeWarning'];
export type TradeSpecResult = components['schemas']['TradeSpecResult'];

export async function scanOpportunities(): Promise<OpportunityScanResult> {
  return restoreTuples(unwrap(await client.GET('/api/opportunity/scan'), 'scan opportunities'));
}

export async function getTradeSpec(playbookId: string): Promise<TradeSpecResult> {
  return unwrap(
    await client.POST('/api/opportunity/spec/{playbook_id}', { params: { path: { playbook_id: playbookId } } }),
    `generate trade spec for ${playbookId}`,
  );
}

// ---- Sprint 5: Post-Mortem, Opportunity Ledger, Performance Diagnostics ----

export type ClosePositionRequest = components['schemas']['ClosePositionRequest'];
export type ClosurePostMortem = components['schemas']['ClosurePostMortemSchema'];
export type OpportunityRecord = components['schemas']['OpportunityRecordSchema'];
export type PlaybookMetrics = components['schemas']['PlaybookMetrics'];
export type PerformanceDiagnostics = components['schemas']['PerformanceDiagnosticsSchema'];

export async function closePosition(positionId: string, req: ClosePositionRequest): Promise<ClosurePostMortem> {
  return unwrap(
    await client.POST('/api/positions/{position_id}/close', {
      params: { path: { position_id: positionId } },
      body: req,
    }),
    'close position',
  );
}

export type RollCandidate = components['schemas']['RollCandidateSchema'];
export type RollLeg = components['schemas']['RollLegSchema'];
export type RollPositionRequest = components['schemas']['RollPositionRequest'];

export async function rollPosition(positionId: string, req: RollPositionRequest): Promise<Position> {
  return restoreTuples(
    unwrap(
      await client.POST('/api/positions/{position_id}/roll', {
        params: { path: { position_id: positionId } },
        body: req,
      }),
      'roll position',
    ),
  );
}

export async function getPostMortems(): Promise<ClosurePostMortem[]> {
  return unwrap(await client.GET('/api/positions/post-mortems'), 'fetch post-mortems');
}

export async function getPostMortem(positionId: string): Promise<ClosurePostMortem> {
  return unwrap(
    await client.GET('/api/positions/{position_id}/post-mortem', { params: { path: { position_id: positionId } } }),
    'fetch post-mortem',
  );
}

export async function getOpportunityLedger(): Promise<OpportunityRecord[]> {
  return unwrap(await client.GET('/api/opportunity/ledger'), 'fetch opportunity ledger');
}

export async function createOpportunityRecord(record: Omit<OpportunityRecord, 'id'>): Promise<OpportunityRecord> {
  return unwrap(
    await client.POST('/api/opportunity/ledger', { body: { ...record, id: '' } }),
    'create opportunity record',
  );
}

export async function updateOpportunityOutcome(recordId: string, outcome_if_taken: number): Promise<OpportunityRecord> {
  return unwrap(
    await client.PATCH('/api/opportunity/ledger/{record_id}', {
      params: { path: { record_id: recordId } },
      body: { outcome_if_taken },
    }),
    'update opportunity outcome',
  );
}

export async function getPerformanceDiagnostics(): Promise<PerformanceDiagnostics> {
  return unwrap(await client.GET('/api/performance/diagnostics'), 'fetch performance diagnostics');
}

export async function refreshPositionPrices(): Promise<Position[]> {
  return restoreTuples(unwrap(await client.POST('/api/positions/refresh'), 'refresh position prices'));
}

// ---- Attention triage (#890): the "what needs you" surface ----

export type AttentionResponse = components['schemas']['AttentionResponse'];
export type AttentionAction = components['schemas']['AttentionAction'];
export type AttentionActionKind = components['schemas']['AttentionActionKind'];
export type HaltItem = components['schemas']['HaltItem'];
export type PositionActionItem = components['schemas']['PositionActionItem'];
export type ReconciliationDriftItem = components['schemas']['ReconciliationDriftItem'];
export type PartialOrderItem = components['schemas']['PartialOrderItem'];
export type FlexDiscrepancyItem = components['schemas']['FlexDiscrepancyItem'];
export type DeliveryGapItem = components['schemas']['DeliveryGapItem'];
export type BrokerErrorItem = components['schemas']['BrokerErrorItem'];
export type UnresolvedUrgentEvent = components['schemas']['UnresolvedUrgentEvent'];

export async function getAttention(): Promise<AttentionResponse> {
  return unwrap(await client.GET('/api/attention'), 'fetch attention');
}

/** One flattened row across every AttentionResponse bucket (halts, p1_actions,
 * reconciliation_drift, ...) — AttentionBlock normalizes into this shape so
 * AttentionItem can render any of them with one component (DESIGN-890.md §4). */
export interface AttentionRowItem {
  id: string;
  title: string;
  detail?: string;
  meta?: string;
  action: AttentionAction;
}

// ---- Supervision console (#73): trading control, books, audit, executor status ----

export type TradingControl = components['schemas']['TradingControlSchema'];
export type ControlState = TradingControl['state'];
export type TradingControlView = components['schemas']['TradingControlView'];
export type LiveGateChecklist = components['schemas']['LiveGateChecklistSchema'];
export type LiveGateCondition = components['schemas']['LiveGateConditionSchema'];
export type TailHedgeMetrics = components['schemas']['TailHedgeMetricsSchema'];
export type BookSummary = components['schemas']['BookSummarySchema'];
export type AuditEvent = components['schemas']['AuditEventSchema'];
export type ExecutorStatus = components['schemas']['ExecutorStatusSchema'];
export type LiveOrder = components['schemas']['LiveOrderSchema'];

export async function getTradingControl(): Promise<TradingControlView> {
  return unwrap(await client.GET('/api/trading-control'), 'fetch trading control');
}

export async function updateTradingControl(scope: string, state: ControlState, reason: string): Promise<TradingControlView> {
  return unwrap(
    await client.POST('/api/trading-control', { body: { scope, state, reason } }),
    'update trading control',
  );
}

export async function getBooks(): Promise<BookSummary[]> {
  return unwrap(await client.GET('/api/books'), 'fetch books').books;
}

export interface AuditEventFilters {
  book_id?: string;
  date?: string;
  event_type?: string;
  limit?: number;
}

export async function getAuditEvents(filters: AuditEventFilters = {}): Promise<AuditEvent[]> {
  return unwrap(
    await client.GET('/api/audit-events', { params: { query: filters } }),
    'fetch audit events',
  );
}

export async function getExecutorStatus(): Promise<ExecutorStatus> {
  return unwrap(await client.GET('/api/executor/status'), 'fetch executor status');
}

// #601: what the system currently believes is resting at the broker.
export async function getLiveOrders(): Promise<LiveOrder[]> {
  return unwrap(await client.GET('/api/orders/live'), 'fetch live orders');
}

// ---- Reconciliation resolution (#310) ----

export type ReconciliationRun = components['schemas']['ReconciliationRunSchema'];
export type CashAdjustmentResult = components['schemas']['CashAdjustmentResult'];

/** Latest reconciliation run, or null when none has happened yet. */
export async function getLatestReconciliation(): Promise<ReconciliationRun | null> {
  const result = await client.GET('/api/reconciliation/latest');
  if (result.response.status === 404) return null;
  return unwrap(result, 'fetch reconciliation run');
}

export async function resolveReconciliation(runId: number, resolution: string): Promise<ReconciliationRun> {
  return unwrap(
    await client.POST('/api/reconciliation/{run_id}/resolve', {
      params: { path: { run_id: runId } },
      body: { resolution },
    }),
    'resolve reconciliation run',
  );
}

export async function recordExternalClose(
  positionId: string, exitValuePerShare: number, reason: string, acknowledgeCancelled = false,
): Promise<ClosurePostMortem> {
  return unwrap(
    await client.POST('/api/resolution/external-close', {
      body: {
        position_id: positionId,
        exit_value_per_share: exitValuePerShare,
        reason,
        acknowledge_cancelled: acknowledgeCancelled,
      },
    }),
    'record external close',
  );
}

export type PartialOrderResolveResult = components['schemas']['PartialOrderResolveResult'];

export async function resolvePartialOrder(orderRef: string, reason: string): Promise<PartialOrderResolveResult> {
  return unwrap(
    await client.POST('/api/resolution/partial-order', {
      body: { order_ref: orderRef, reason },
    }),
    'resolve partial order',
  );
}

export type FlexAckResult = components['schemas']['FlexAckResult'];

export async function ackFlexDiscrepancies(execIds: string[], reason: string): Promise<FlexAckResult> {
  return unwrap(
    await client.POST('/api/resolution/flex-ack', {
      body: { exec_ids: execIds, reason },
    }),
    'acknowledge Flex discrepancies',
  );
}

// ---- Analysis tab (#242-#244) ----

export type FillQualityReport = components['schemas']['FillQualityReport'];

export async function getFillQuality(): Promise<FillQualityReport> {
  return unwrap(await client.GET('/api/analysis/fill-quality'), 'fetch fill-quality report');
}

export type LeaderboardReport = components['schemas']['LeaderboardReport'];
export type KnobSweep = components['schemas']['KnobSweepSchema'];

export async function getLeaderboard(): Promise<LeaderboardReport> {
  return unwrap(await client.GET('/api/analysis/leaderboard'), 'fetch leaderboard report');
}

export type RegimeHitRateReport = components['schemas']['RegimeHitRateReport'];

export async function getRegimeHitRate(): Promise<RegimeHitRateReport> {
  return unwrap(await client.GET('/api/analysis/regime-hit-rate'), 'fetch regime hit-rate report');
}

export type EvidenceVerdict = components['schemas']['EvidenceVerdictSchema'];

export async function getEvidenceVerdict(): Promise<EvidenceVerdict> {
  return unwrap(await client.GET('/api/analysis/evidence-verdict'), 'fetch evidence verdict');
}

export async function adjustBookCash(bookId: string, delta: number, reason: string): Promise<CashAdjustmentResult> {
  return unwrap(
    await client.POST('/api/resolution/cash', { body: { book_id: bookId, delta, reason } }),
    'adjust book cash',
  );
}
